import csv
import pandas as pd

# Dicionário de tradução de cargos
translations = {
    "Solutions Engineer": "Engenheiro de Soluções",
    "Data Engineer": "Engenheiro de Dados",
    "Data Scientist": "Cientista de Dados",
    "BI Developer": "Desenvolvedor de BI",
    "Data Analyst": "Analista de Dados",
    "Applied Scientist": "Cientista Aplicado",
    "Systems Engineer": "Engenheiro de Sistemas",
    "Director": "Diretor",
    "Associate": "Associado",
    "Software Engineer": "Engenheiro de Software",
    "Consultant": "Consultor",
    "Analyst": "Analista",
    "Product Manager": "Gerente de Produto",
    "Software Developer": "Desenvolvedor de Software",
    "Engineer": "Engenheiro",
    "Developer": "Desenvolvedor",
    "Data Specialist": "Especialista de Dados",
    "Manager": "Gerente",
    "Research Scientist": "Cientista de Pesquisa",
    "Software Architect": "Arquiteto de Software",
    "Data Management Analyst": "Analista de Gerenciamento de Dados",
    "Data Reporter": "Repórter de Dados",
    "Computational Biologist": "Biólogo Computacional",
    "Product Designer": "Designer de Produto",
    "Software Development Engineer": "Engenheiro de Desenvolvimento de Software",
    "Architect": "Arquiteto",
    "Data Analytics Manager": "Gerente de Análise de Dados",
    "Principal Statistical Programmer": "Programador Estatístico Principal",
    "Cloud Engineer": "Engenheiro de Nuvem",
    "Data Architect": "Arquiteto de Dados",
    "Product Owner": "Dono do Produto",
    "Business Intelligence Engineer": "Engenheiro de Business Intelligence",
    "Data Governance Lead": "Líder de Governança de Dados",
    "Data Governance Specialist": "Especialista em Governança de Dados",
    "AI Engineer": "Engenheiro de IA",
    "Solutions Architect": "Arquiteto de Soluções",
    "AI Researcher": "Pesquisador de IA",
    "Machine Learning Engineer": "Engenheiro de Machine Learning",
    "Data Strategist": "Estrategista de Dados",
    "Research Engineer": "Engenheiro de Pesquisa",
    "Researcher": "Pesquisador",
    "Business Analyst": "Analista de Negócios",
    "Solution Engineer": "Engenheiro de Soluções",
    "Full Stack Developer": "Desenvolvedor Full Stack",
    "Product Analyst": "Analista de Produto",
    "Full Stack Engineer": "Engenheiro Full Stack",
    "Backend Engineer": "Engenheiro Backend",
    "Sales Engineer": "Engenheiro de Vendas",
    "Prompt Engineer": "Engenheiro de Prompt",
    "Head of AI": "Chefe de IA",
    "Platform Engineer": "Engenheiro de Plataforma",
    "Analytics Engineer": "Engenheiro de Analytics",
    "Engineering Manager": "Gerente de Engenharia",
    "BI Engineer": "Engenheiro de BI",
    "Systems Administrator": "Administrador de Sistemas",
    "Site Reliability Engineer": "Engenheiro de Confiabilidade de Sites",
    "Computer Vision Engineer": "Engenheiro de Visão Computacional",
    "Data Operations Analyst": "Analista de Operações de Dados",
    "MLOps Engineer": "Engenheiro de MLOps",
    "Solution Architect": "Arquiteto de Soluções",
    "Data Platform Engineer": "Engenheiro de Plataforma de Dados",
    "Artificial Intelligence Engineer": "Engenheiro de Inteligência Artificial",
    "ML Scientist": "Cientista de ML",
    "Data Governance Manager": "Gerente de Governança de Dados",
    "Data Manager": "Gerente de Dados",
    "Machine Learning Scientist": "Cientista de Machine Learning",
    "Data Management": "Gerenciamento de Dados",
    "Data Product Owner": "Dono do Produto de Dados",
    "Data Analytics Specialist": "Especialista em Análise de Dados",
    "Head of Data": "Chefe de Dados",
    "Data Analysis": "Análise de Dados",
    "Data Quality Lead": "Líder de Qualidade de Dados",
    "Tech Lead": "Líder Técnico",
    "Business Intelligence Specialist": "Especialista em Business Intelligence",
    "Business Intelligence Analyst": "Analista de Business Intelligence",
    "Data Modeler": "Modelador de Dados",
    "Cloud Database Engineer": "Engenheiro de Banco de Dados em Nuvem",
    "Data Lead": "Líder de Dados",
    "Tableau Developer": "Desenvolvedor Tableau",
    "Lead Engineer": "Engenheiro Líder",
    "Data Quality Analyst": "Analista de Qualidade de Dados",
    "Technical Architect": "Arquiteto Técnico",
    "Data Governance": "Governança de Dados",
    "Encounter Data Management Professional": "Profissional de Gerenciamento de Dados de Encontros",
    "Data and Reporting Professional": "Profissional de Dados e Relatórios",
    "Cloud Database Administrator": "Administrador de Banco de Dados em Nuvem",
    "Research Assistant": "Assistente de Pesquisa",
    "Postdoctoral Fellow": "Bolsista de Pós-Doutorado",
    "Analytics Lead": "Líder de Analytics",
    "Creative Technologist": "Tecnólogo Criativo",
    "Member of Technical Staff": "Membro da Equipe Técnica",
    "Quantitative Researcher": "Pesquisador Quantitativo",
    "Machine Learning Researcher": "Pesquisador de Machine Learning",
    "Research Associate": "Associado de Pesquisa",
    "Data Integration Engineer": "Engenheiro de Integração de Dados",
    "AI Developer": "Desenvolvedor de IA",
    "Postdoctoral Researcher": "Pesquisador de Pós-Doutorado",
    "Power BI Developer": "Desenvolvedor Power BI",
    "Data Product Manager": "Gerente de Produto de Dados",
    "Actuary": "Atuário",
    "Quantitative Analyst": "Analista Quantitativo",
    "Statistician": "Estatístico",
    "Big Data Developer": "Desenvolvedor Big Data",
    "Data Operations": "Operações de Dados",
    "Analytics Specialist": "Especialista em Analytics",
    "Director of Product Management": "Diretor de Gerenciamento de Produto",
    "Business Development Representative": "Representante de Desenvolvimento de Negócios",
    "Director of Machine Learning": "Diretor de Machine Learning",
    "Head of Machine Learning": "Chefe de Machine Learning",
    "Clinical Aide": "Auxiliar Clínico",
    "AI Governance Specialist": "Especialista em Governança de IA",
    "AI Strategist": "Estrategista de IA",
    "Data Analist": "Analista de Dados",
    "AI Product Lead": "Líder de Produto de IA",
    "Data Integration Specialist": "Especialista em Integração de Dados",
    "Data Visualization Developer": "Desenvolvedor de Visualização de Dados",
    "AI Product Owner": "Dono do Produto de IA",
    "Data Infrastructure Engineer": "Engenheiro de Infraestrutura de Dados",
    "Principal Engineer": "Engenheiro Principal",
    "Data Analytics Business Partner": "Parceiro de Negócios de Análise de Dados",
    "Data Operations Specialist": "Especialista em Operações de Dados",
    "Data Operations Engineer": "Engenheiro de Operações de Dados",
    "AI Engineering Lead": "Líder de Engenharia de IA",
    "Marketing Science Partner": "Parceiro de Ciência de Marketing",
    "Software Development Director": "Diretor de Desenvolvimento de Software",
    "Power BI Expert": "Especialista em Power BI",
    "BI & Data Analyst": "Analista de BI e Dados",
    "Network Engineer": "Engenheiro de Rede",
    "Technical Support Engineer": "Engenheiro de Suporte Técnico",
    "Technical Support Specialist": "Especialista em Suporte Técnico",
    "Technical Writer": "Redator Técnico",
    "Technical Recruiter": "Recrutador Técnico",
    "Database Administrator": "Administrador de Banco de Dados",
    "Data Quality Engineer": "Engenheiro de Qualidade de Dados",
    "Post Doctoral Fellow": "Bolsista de Pós-Doutorado",
    "Insight Analyst": "Analista de Insights",
    "Application Developer": "Desenvolvedor de Aplicativos",
    "Enterprise Account Executive": "Executivo de Contas Empresariais",
    "Account Executive": "Executivo de Contas",
    "Executive": "Executivo",
    "Trainee": "Trainee",
    "Quant Trader": "Trader Quantitativo",
    "Bioinformatician": "Bioinformata",
    "Bioinformatics Specialist": "Especialista em Bioinformática",
    "AI Data Scientist": "Cientista de Dados de IA",
    "Research Professional": "Profissional de Pesquisa",
    "Power BI": "Power BI",
    "Chatbot Developer": "Desenvolvedor de Chatbot",
    "Cloud Developer": "Desenvolvedor de Nuvem",
    "Algorithm Developer": "Desenvolvedor de Algoritmos",
    "Data Team Lead": "Líder de Equipe de Dados",
    "Security Researcher": "Pesquisador de Segurança",
    "Data Steward": "Administrador de Dados",
    "Web Developer": "Desenvolvedor Web",
    "AI Solutions Specialist": "Especialista em Soluções de IA",
    "Data Integrator": "Integrador de Dados",
    "AI Content Writer": "Redator de Conteúdo de IA",
    "Principal Scientist": "Cientista Principal",
    "Economist": "Economista",
    "System Engineer": "Engenheiro de Sistemas",
    "System Administrator": "Administrador de Sistemas",
    "Bear Robotics": "Bear Robotics",
    "Business Intelligence": "Business Intelligence",
    "BI Analyst": "Analista de BI",
    "Data Visualization Specialist": "Especialista em Visualização de Dados",
    "DevOps Engineer": "Engenheiro DevOps",
    "DevOps Lead": "Líder DevOps",
    "Risk Analyst": "Analista de Risco",
    "Salesforce Administrator": "Administrador Salesforce",
    "Data Analytics Lead": "Líder de Análise de Dados",
    "Data Governance Consultant": "Consultor de Governança de Dados",
    "Data Operator": "Operador de Dados",
    "AI Tech Lead": "Líder Técnico de IA",
    "Machine Learning Architect": "Arquiteto de Machine Learning",
    "Data Science": "Ciência de Dados",
    "Head of Marketing": "Chefe de Marketing",
    "Data Consultant": "Consultor de Dados",
    "Psychometrician": "Psicometrista",
    "Power BI Administrator": "Administrador de Power BI",
    "Data Reporting Specialist": "Especialista em Relatórios de Dados",
    "Research Team Lead": "Líder de Equipe de Pesquisa",
    "Analytics Engineering Manager": "Gerente de Engenharia de Analytics",
    "Applied AI ML Lead": "Líder de IA e ML Aplicado",
    "Head of Applied AI": "Chefe de IA Aplicada",
    "Machine Learning Performance Engineer": "Engenheiro de Performance de Machine Learning",
    "AWS Data Architect": "Arquiteto de Dados AWS",
    "Data Science Tech Lead": "Líder Técnico de Ciência de Dados"
}

input_file = '/home/geovane/site/aula4/dados_tratados.csv'

# Lê o arquivo, traduz e sobrescreve
rows = []
with open(input_file, mode='r', encoding='utf-8') as infile:
    reader = csv.DictReader(infile)
    fieldnames = reader.fieldnames
    for row in reader:
        cargo_en = row['cargo']
        if cargo_en in translations:
            row['cargo'] = translations[cargo_en]
        rows.append(row)

with open(input_file, mode='w', encoding='utf-8', newline='') as outfile:
    writer = csv.DictWriter(outfile, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows)

print(f"Cargos traduzidos no arquivo: {input_file}")


# Nome do arquivo de dados
ARQUIVO = "dados_tratados.csv"

def traduzir():
    print(f"Lendo {ARQUIVO}...")
    try:
        df = pd.read_csv(ARQUIVO)
    except FileNotFoundError:
        print(f"Erro: Arquivo {ARQUIVO} não encontrado. Execute 'python etl.py' primeiro.")
        return

    # Dicionário de tradução de cargos (Inglês -> Português)
    mapa_cargos = {
        "Software Development Engineer": "Engenheiro de Desenvolvimento de Software",
        "Data Scientist": "Cientista de Dados",
        "Data Analyst": "Analista de Dados",
        "Data Engineer": "Engenheiro de Dados",
        "Machine Learning Engineer": "Engenheiro de Machine Learning",
        "Analytics Engineer": "Engenheiro de Analytics",
        "Research Scientist": "Cientista Pesquisador",
        "Data Architect": "Arquiteto de Dados",
        "Business Intelligence Engineer": "Engenheiro de BI",
        "Applied Scientist": "Cientista Aplicado",
        "Research Engineer": "Engenheiro de Pesquisa",
        "Data Science Manager": "Gerente de Ciência de Dados",
        "Head of Data": "Chefe de Dados",
        "Data Specialist": "Especialista de Dados",
        "Data Manager": "Gerente de Dados",
        "Machine Learning Scientist": "Cientista de Machine Learning",
        "ML Engineer": "Engenheiro de ML",
        "Lead Data Scientist": "Cientista de Dados Líder",
        "Director of Data Science": "Diretor de Ciência de Dados",
        "Lead Data Engineer": "Engenheiro de Dados Líder",
        "Data Science Consultant": "Consultor de Ciência de Dados",
        "AI Scientist": "Cientista de IA",
        "BI Data Analyst": "Analista de BI",
        "Computer Vision Engineer": "Engenheiro de Visão Computacional",
        "Data Analytics Manager": "Gerente de Analytics",
        "Business Data Analyst": "Analista de Dados de Negócios",
        "Big Data Engineer": "Engenheiro de Big Data",
        "Data Science Lead": "Líder de Ciência de Dados",
        "Data Analytics Engineer": "Engenheiro de Analytics",
        "Principal Data Engineer": "Engenheiro de Dados Principal",
        "Machine Learning Software Engineer": "Engenheiro de Software de ML",
        "Cloud Data Engineer": "Engenheiro de Dados em Nuvem",
        "Financial Data Analyst": "Analista de Dados Financeiros",
        "Data Infrastructure Engineer": "Engenheiro de Infraestrutura de Dados",
        "Applied Machine Learning Scientist": "Cientista de ML Aplicado",
        "Data Operations Engineer": "Engenheiro de Operações de Dados",
        "Deep Learning Engineer": "Engenheiro de Deep Learning",
        "BI Analyst": "Analista de BI",
        "Data Science Engineer": "Engenheiro de Ciência de Dados",
        "Head of Data Science": "Chefe de Ciência de Dados",
        "Insight Analyst": "Analista de Insights",
        "Data Analytics Consultant": "Consultor de Analytics",
        "Big Data Architect": "Arquiteto de Big Data",
        "Product Data Analyst": "Analista de Dados de Produto",
        "Computer Vision Software Engineer": "Engenheiro de Software de Visão Computacional",
        "Azure Data Engineer": "Engenheiro de Dados Azure",
        "Marketing Data Analyst": "Analista de Dados de Marketing",
        "Principal Data Analyst": "Analista de Dados Principal",
        "Data Analytics Lead": "Líder de Analytics",
        "Staff Data Scientist": "Cientista de Dados Staff",
        "Lead Data Analyst": "Analista de Dados Líder",
        "Machine Learning Research Engineer": "Engenheiro de Pesquisa em ML",
        "Machine Learning Manager": "Gerente de Machine Learning",
        "Data Engineering Manager": "Gerente de Engenharia de Dados",
        "Cloud Database Engineer": "Engenheiro de Banco de Dados em Nuvem",
        "NLP Engineer": "Engenheiro de NLP",
        "Machine Learning Developer": "Desenvolvedor de Machine Learning",
        "Applied Data Scientist": "Cientista de Dados Aplicado",
        "ETL Developer": "Desenvolvedor ETL",
        "Data Quality Analyst": "Analista de Qualidade de Dados",
        "AI Developer": "Desenvolvedor de IA",
        "Data Strategist": "Estrategista de Dados",
        "Finance Data Analyst": "Analista de Dados Financeiros",
        "Compliance Data Analyst": "Analista de Dados de Compliance",
        "Data Science Tech Lead": "Líder Técnico de Ciência de Dados",
        "Staff Data Engineer": "Engenheiro de Dados Staff",
        "Product Data Scientist": "Cientista de Dados de Produto",
        "Data Visualization Specialist": "Especialista em Visualização de Dados",
        "Head of Machine Learning": "Chefe de Machine Learning",
        "Data Operations Analyst": "Analista de Operações de Dados",
        "Research Team Lead": "Líder de Equipe de Pesquisa",
        "Analytics Engineering Manager": "Gerente de Engenharia de Analytics",
        "Applied AI ML Lead": "Líder de IA e ML Aplicado",
        "Head of Applied AI": "Chefe de IA Aplicada",
        "Machine Learning Performance Engineer": "Engenheiro de Performance de Machine Learning",
        "AWS Data Architect": "Arquiteto de Dados AWS",
        "Director of Product Management": "Diretor de Gerenciamento de Produto",
        "Engineering Manager": "Gerente de Engenharia"
    }

    if 'cargo' in df.columns:
        df['cargo'] = df['cargo'].replace(mapa_cargos)
        df.to_csv(ARQUIVO, index=False)
        print(f"Sucesso! Cargos traduzidos e salvos em {ARQUIVO}.")

if __name__ == "__main__":
    traduzir()
